---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: quotes
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kustomize
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: quotes
  targetNamespace: default
  timeout: 2m0s
  wait: true
