---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: quotes
  namespace: flux-system
spec:
  interval: 2m0s
  ref:
    branch: main
  url: https://github.com/khabdrick/roll-flux
